['.oh-my-zsh/custom/themes/powerlevel10k']
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

['.config/i3/scripts/twm-status-builder']
    type = "archive"
    url = "https://github.com/kantord/twm-status-builder/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"


['.oh-my-zsh/custom/plugins/zsh-vi-mode']
    type = "archive"
    url = "https://github.com/jeffreytse/zsh-vi-mode/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

