['.oh-my-zsh/custom/themes/powerlevel10k']
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

['.config/i3/scripts/twm-status-builder']
    type = "archive"
    url = "https://github.com/kantord/twm-status-builder/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

{{ if eq .isRoverEnv "true" }}
[".config/pawfect.nvim"]
    type = "git-repo"
    url = "https://github.com/roverdotcom/pawfect.nvim.git"
    refreshPeriod = "168h"
{{ end }}
