#!/usr/bin/env bash
set -euo pipefail

kitty_config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
kitty_theme_primary="$kitty_config_dir/themes.conf"
kitty_theme_fallback="$kitty_config_dir/current-theme.conf"
out_dir="${XDG_CONFIG_HOME:-$HOME/.config}/i3"
bar_out_file="$out_dir/kitty-bar.conf"
client_out_file="$out_dir/kitty-client-colors.conf"

declare -A visited=()

extract_bg_from_file() {
  local file="$1"
  local line included_file_path included_file_raw

  [[ -r "$file" ]] || return 1
  [[ -n "${visited[$file]:-}" ]] && return 1
  visited["$file"]=1

  while IFS= read -r line; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue

    if [[ "$line" =~ ^[[:space:]]*background[[:space:]]+(#[0-9a-fA-F]{6,8})\b ]]; then
      printf '%s\n' "${BASH_REMATCH[1]}"
      return 0
    fi

    if [[ "$line" =~ ^[[:space:]]*include[[:space:]]+(.+)$ ]]; then
      included_file_raw="${BASH_REMATCH[1]}"
      included_file_raw="${included_file_raw%%#*}"
      included_file_raw="$(printf '%s' "$included_file_raw" | xargs)"
      [[ -z "$included_file_raw" ]] && continue

      if [[ "$included_file_raw" = /* ]]; then
        included_file_path="$included_file_raw"
      else
        included_file_path="$kitty_config_dir/$included_file_raw"
      fi

      if extract_bg_from_file "$included_file_path"; then
        return 0
      fi
    fi
  done <"$file"

  return 1
}

kitty_bg="$(
  # Most reliable: kitty writes the active theme colors here.
  if [[ -r "$kitty_config_dir/current-theme.conf" ]]; then
    grep -m1 -E '^[[:space:]]*background[[:space:]]+#' "$kitty_config_dir/current-theme.conf" \
      | awk '{print $2}' && exit 0
  fi

  # If we are running inside kitty, query the colors directly.
  if command -v kitty >/dev/null 2>&1; then
    kitty @ get-colors 2>/dev/null | awk '$1 == "background" { print $2; exit }' && exit 0
  fi

  # Fallback: parse config files and follow include directives.
  extract_bg_from_file "$kitty_theme_primary" || extract_bg_from_file "$kitty_theme_fallback" || printf '%s\n' '#000000'
)"

kitty_fg="$(
  if [[ -r "$kitty_config_dir/current-theme.conf" ]]; then
    grep -m1 -E '^[[:space:]]*foreground[[:space:]]+#' "$kitty_config_dir/current-theme.conf" \
      | awk '{print $2}' && exit 0
  fi

  if command -v kitty >/dev/null 2>&1; then
    kitty @ get-colors 2>/dev/null | awk '$1 == "foreground" { print $2; exit }' && exit 0
  fi

  printf '%s\n' '#ffffff'
)"

kitty_yellow="$(
  if [[ -r "$kitty_config_dir/current-theme.conf" ]]; then
    # Prefer bright yellow (color11), fall back to yellow (color3)
    grep -m1 -E '^[[:space:]]*color11[[:space:]]+#' "$kitty_config_dir/current-theme.conf" \
      | awk '{print $2}' && exit 0
    grep -m1 -E '^[[:space:]]*color3[[:space:]]+#' "$kitty_config_dir/current-theme.conf" \
      | awk '{print $2}' && exit 0
  fi
  printf '%s\n' '#F6A100'
)"

hex6() {
  local c="${1:-}"
  c="${c#\#}"
  c="${c:0:6}"
  printf '%s\n' "$c"
}

blend_hex() {
  # Usage: blend_hex BG FG -> mostly BG, slightly FG (subtle border color)
  local bg_hex fg_hex r g b br bg bb fr fg fb
  bg_hex="$(hex6 "$1")"
  fg_hex="$(hex6 "$2")"

  br=$((16#${bg_hex:0:2})); bg=$((16#${bg_hex:2:2})); bb=$((16#${bg_hex:4:2}))
  fr=$((16#${fg_hex:0:2})); fg=$((16#${fg_hex:2:2})); fb=$((16#${fg_hex:4:2}))

  # 80% bg + 20% fg
  r=$(((br * 4 + fr) / 5))
  g=$(((bg * 4 + fg) / 5))
  b=$(((bb * 4 + fb) / 5))
  printf '#%02x%02x%02x\n' "$r" "$g" "$b"
}

kitty_ws_border="$(blend_hex "$kitty_bg" "$kitty_fg" 2>/dev/null || printf '%s\n' '#444444')"

mkdir -p "$out_dir"

umask 077
cat >"$bar_out_file" <<EOF
bar {
  status_command "bash /home/kantord/.config/i3/status_command.sh"
  colors {
    background $kitty_bg
    statusline $kitty_fg
    separator  $kitty_fg
    # Focused output's active workspace: filled (more prominent).
    focused_workspace $kitty_ws_border $kitty_ws_border $kitty_fg
    # Other outputs' active workspaces: outlined (less prominent).
    active_workspace  $kitty_ws_border $kitty_bg $kitty_fg
    inactive_workspace $kitty_bg    $kitty_bg     $kitty_fg
    urgent_workspace  #ff0000      #ff0000      #ffffff
  }
}
EOF

cat >"$client_out_file" <<EOF
# Auto-generated by ~/.config/i3/sync_i3bar_with_kitty_theme.sh
# class                 border      backgr.     text     indicator child_border
client.focused          $kitty_yellow $kitty_yellow #000000  #2e9ef4   $kitty_yellow
client.focused_inactive $kitty_bg   $kitty_bg   #ffffff  #484e50   $kitty_bg
client.unfocused        $kitty_bg   $kitty_bg   #888888  #292d2e   $kitty_bg
client.placeholder      $kitty_bg   $kitty_bg   #ffffff  #0e101a   $kitty_bg
client.background       $kitty_bg
EOF

set_root_background() {
  local color="$1"

  if [[ -n "${DISPLAY:-}" ]]; then
    if command -v hsetroot >/dev/null 2>&1 && hsetroot -solid "$color" >/dev/null 2>&1; then
      return 0
    fi
    if command -v xsetroot >/dev/null 2>&1 && xsetroot -solid "$color" >/dev/null 2>&1; then
      return 0
    fi
  fi

  if command -v i3-msg >/dev/null 2>&1; then
    if command -v hsetroot >/dev/null 2>&1; then
      # i3 runs exec commands via sh; the color must be quoted since it starts with '#'.
      i3-msg "exec --no-startup-id hsetroot -solid '$color'" >/dev/null 2>&1 && return 0
    fi
    if command -v xsetroot >/dev/null 2>&1; then
      i3-msg "exec --no-startup-id xsetroot -solid '$color'" >/dev/null 2>&1 && return 0
    fi
  fi

  return 1
}

set_root_background "$kitty_bg" || true
