neovim-bin = "/home/kantord/.local/bin/lvim"

[font]
size = 20
hinting = "none"
edging = "subpixelantialias"
normal = "Monaspace Neon"
italic = "Monaspace Radon"
bold = "Monaspace Xenon"

[font.features]
"Monaspace Neon" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08" ]
"Monaspace Radon" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08" ]
"Monaspace Xenon" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08" ]
