-- require "nvchad.mappings"
--
-- -- add yours here
--
-- local map = vim.keymap.set
-- local builtin = require('telescope.builtin')
--
-- map("n", ";", ":", { desc = "CMD enter command mode" })
-- map("i", "jk", "<ESC>")
--
--
-- map('n', '<leader>j', builtin.find_files, { })
--
-- if vim.g.neovide == true then
--   vim.api.nvim_set_keymap("n", "<C-+>", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor + 0.1<CR>", { silent = true })
--   vim.api.nvim_set_keymap("n", "<C-->", ":lua vim.g.neovide_scale_factor = vim.g.neovide_scale_factor - 0.1<CR>", { silent = true })
--   vim.api.nvim_set_keymap("n", "<C-0>", ":lua vim.g.neovide_scale_factor = 1<CR>", { silent = true })
-- end
--
-- require("telescope").setup {
--   defaults = {
--     vimgrep_arguments = {
--       "zg",
--       "--column",
--       "--color=never",
--     },
--   },
-- }

-- map({ "n", "i", "v" }, "<C-s>", "<cmd> w <cr>")
