name: build-mac

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - run: ./setup.sh
      - name: print package list
        run: cat ~/.required-packages.txt | tr -d ' ' | grep -v "^$" | sort -u
