name: build-linux
on:
  push:
  pull_request:

jobs:
  clone-and-install:
    strategy:
      matrix:
        os: ["archlinux:latest"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix. os }}
    steps:
      - uses: actions/checkout@v2
      - run: ./setup.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
      - name: print package list
        run: cat ~/.required-packages.txt | tr -d ' ' | grep -v "^$" | sort -u
